site_name: Harvey OS
site_description: A distributed operating system 
site_url: http://harvey-os.org
site_favicon: img/favicon.png
# copyright
# google_analytics
pages:
  - Home: index.md
  - About: about.md 
  - News: news.md
  - Download: download.md
  - Community: community.md
  - Blog : blog.md
  - Donate: donate.md
# - GSOC: gsoc.md
#  - Documentation: 
#    - FAQ: docs/faq.md
#    - Getting started: docs/getting-started.md
#    - Manual: docs/manual.md
#theme: barehare
theme_dir: barehare_theme
repo_url: https://github.com/Harvey-OS/harvey
copyright: The Harvey OS Team
extra:
  toc_pages:
    - News
  meta_desc:
    - About: "Harvey OS About page is where you come to see who is behind the madness. Unix admins, Plan 9 admirers, system programmers, C & assembler devotees. And even stranger things."
    - News: "News and events around Harvey OS, sharing resources."
    - Download: "Harvey OS software releases."
    - Community: "The Harvey community assists, directly or indirectly, to the development and promotion of Harvey OS. This page lists the places were people and groups around the Harvey OS project gather."
    - Donate: "Help Harvey OS community with donations."

