site_name: Harvey OS
site_description: A Fresh Take on Plan 9 
site_url: http://harvey-os.org
site_favicon: img/icon/favicon.png
# copyright
# google_analytics
pages:
  - Home: index.md
  - About: about.md 
  - News: news.md
  - Download: download.md
  - Community: community.md
  - Blog : blog.md
# - GSOC: gsoc.md
#  - Documentation: 
#    - FAQ: docs/faq.md
#    - Getting started: docs/getting-started.md
#    - Manual: docs/manual.md
#theme: barehare
theme_dir: barehare_theme
repo_url: https://github.com/Harvey-OS/harvey
copyright: The Harvey OS Team
extra:
  toc_pages:
    - News
